#!/usr/bin/env python3
"""Generate the SNAME-informed NIMENA public ecosystem pages from one site template."""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TEMPLATE = (ROOT / "programmes" / "index.html").read_text(encoding="utf-8")


PAGES = {
    "membership": {
        "title": "Membership & Professional Community | NIMENA",
        "description": "Explore NIMENA membership benefits, professional pathways, application and renewal steps, chapters, committees and member services.",
        "main": r'''
<main>
<section class="nimena-hub-hero" style="--hub-image:url('../assets/img/current/member-industrial-visit.webp')"><div class="container"><div class="nimena-hub-hero__content">
<span class="nimena-programme-eyebrow">Membership &amp; professional community</span>
<h1>Belong to the profession shaping Nigeria's maritime future.</h1>
<p>Build professional standing, technical capability and trusted connections through a membership journey designed for students, graduates, practising professionals and organisations.</p>
<div class="nimena-programme-actions"><a class="nimena-programme-action" href="../register/">Apply for membership</a><a class="nimena-programme-action nimena-programme-action--outline" href="../login/">Renew or manage membership</a></div>
</div></div></section>
<nav class="nimena-action-strip" aria-label="Membership actions"><div class="container"><div class="nimena-action-strip__grid">
<a href="#benefits"><i class="fa-light fa-badge-check"></i><span><small>Discover</small>Member benefits</span></a>
<a href="#pathways"><i class="fa-light fa-id-card"></i><span><small>Compare</small>Membership pathways</span></a>
<a href="#application"><i class="fa-light fa-file-signature"></i><span><small>Understand</small>Application process</span></a>
<a href="../community/"><i class="fa-light fa-users"></i><span><small>Connect</small>Chapters &amp; communities</span></a>
</div></div></nav>
<section class="nimena-hub-section" id="benefits"><div class="container"><div class="nimena-hub-heading"><div><span class="nimena-programme-number">MEMBER VALUE</span><h2>A professional relationship that grows with your career.</h2></div><p>NIMENA membership should make it easier to learn, contribute, connect and demonstrate continuing professional engagement.</p></div>
<div class="nimena-hub-grid nimena-hub-grid--three">
<article class="nimena-hub-card"><i class="fa-light fa-award"></i><h3>Professional standing</h3><p>A recognised membership pathway with transparent grade, status and renewal records.</p></article>
<article class="nimena-hub-card"><i class="fa-light fa-chart-line-up"></i><h3>CPD &amp; lifelong learning</h3><p>Courses, webinars, attendance records and certificates connected to your member profile.</p></article>
<article class="nimena-hub-card"><i class="fa-light fa-books"></i><h3>Technical knowledge</h3><p>Journals, reports, standards conversations, magazine features and research opportunities.</p></article>
<article class="nimena-hub-card"><i class="fa-light fa-handshake"></i><h3>Industry connections</h3><p>Professional events, technical communities, mentoring and industry collaboration.</p></article>
<article class="nimena-hub-card"><i class="fa-light fa-microscope"></i><h3>Research profile</h3><p>ORCID, publications, reviewing activity and scholarly contributions linked in one place.</p></article>
<article class="nimena-hub-card"><i class="fa-light fa-briefcase"></i><h3>Career development</h3><p>Opportunities, career resources, volunteer roles and routes into professional leadership.</p></article>
</div></div></section>
<section class="nimena-hub-section nimena-hub-section--navy" id="pathways"><div class="container"><div class="nimena-hub-heading"><div><span class="nimena-programme-number">CURRENT APPLICATION PATHWAYS</span><h2>Choose the route that matches your present stage.</h2></div><p>The names below follow NIMENA's current membership application material. Final eligibility, fees and advancement rules remain subject to formal approval.</p></div>
<div class="nimena-pathway-grid">
<article><span>01</span><h3>Corporate</h3><p>Professional individual membership for suitably qualified and experienced practitioners.</p></article>
<article><span>02</span><h3>Associate</h3><p>An affiliate professional route for people contributing to the maritime field.</p></article>
<article><span>03</span><h3>Graduate</h3><p>A pathway for eligible engineering graduates building supervised experience.</p></article>
<article><span>04</span><h3>Student</h3><p>Early professional connection for students in relevant disciplines.</p></article>
<article><span>05</span><h3>Corporate Firm</h3><p>Institutional membership for eligible companies and organisations.</p></article>
</div></div></section>
<section class="nimena-hub-section" id="application"><div class="container"><div class="nimena-hub-heading"><div><span class="nimena-programme-number">APPLICATION &amp; RENEWAL</span><h2>A clear journey from interest to good standing.</h2></div><p>Applicants and members should always know what is required, who is reviewing it and what happens next.</p></div>
<div class="nimena-step-grid">
<article><b>01</b><h3>Create an account</h3><p>Verify your email and begin the appropriate membership application.</p></article>
<article><b>02</b><h3>Submit evidence</h3><p>Provide qualifications, experience, referees and required supporting documents.</p></article>
<article><b>03</b><h3>Professional review</h3><p>The Secretariat checks completeness and authorised reviewers assess eligibility.</p></article>
<article><b>04</b><h3>Decision &amp; payment</h3><p>Approved applicants receive the correct fee, membership number and confirmation.</p></article>
<article><b>05</b><h3>Maintain standing</h3><p>Renew, record CPD, update your profile and apply for grade advancement when eligible.</p></article>
</div></div></section>
<section class="nimena-hub-section nimena-hub-section--soft"><div class="container"><div class="nimena-split-feature"><div class="nimena-split-feature__image"><img src="../assets/img/nimena/archive/gallery-conference.webp" alt="NIMENA members at a professional gathering" loading="lazy"/></div><div><span class="nimena-programme-number">COMMUNITY</span><h2>Professional relationships beyond an application form.</h2><p>Chapters, technical participation, student and young-professional activity, mentoring and volunteering turn membership into an active professional community.</p><div class="nimena-programme-actions"><a class="nimena-programme-action" href="../community/">Explore the community</a><a class="nimena-programme-action nimena-programme-action--outline" href="../login/">Open member portal</a></div></div></div></div></section>
<section class="nimena-hub-cta"><div class="container"><div><span>Ready when you are</span><h2>Apply, renew or ask Member Services for guidance.</h2></div><div><a href="../register/">Apply for membership</a><a href="../contact/">Contact Member Services</a></div></div></section>
</main>''',
    },
    "community": {
        "title": "Chapters, Committees & Communities | NIMENA",
        "description": "Connect with NIMENA chapters, technical participation, students, young professionals, mentors and volunteer opportunities.",
        "main": r'''
<main>
<section class="nimena-hub-hero" style="--hub-image:url('../assets/img/current/singapore-innovation-night.webp')"><div class="container"><div class="nimena-hub-hero__content"><span class="nimena-programme-eyebrow">Chapters, committees &amp; communities</span><h1>Your professional network should feel close—even when the industry is wide.</h1><p>Find routes to local activity, technical contribution, student and early-career support, mentoring and institutional service.</p><div class="nimena-programme-actions"><a class="nimena-programme-action" href="../membership/">Membership information</a><a class="nimena-programme-action nimena-programme-action--outline" href="../login/">Member portal</a></div></div></div></section>
<nav class="nimena-action-strip" aria-label="Community routes"><div class="container"><div class="nimena-action-strip__grid"><a href="#chapters"><i class="fa-light fa-map-location-dot"></i><span><small>Local</small>Chapters &amp; sections</span></a><a href="#technical"><i class="fa-light fa-gears"></i><span><small>Contribute</small>Technical communities</span></a><a href="#emerging"><i class="fa-light fa-user-graduate"></i><span><small>Develop</small>Students &amp; young professionals</span></a><a href="#volunteer"><i class="fa-light fa-hand-holding-heart"></i><span><small>Serve</small>Volunteer with NIMENA</span></a></div></div></nav>
<section class="nimena-hub-section" id="chapters"><div class="container"><div class="nimena-hub-heading"><div><span class="nimena-programme-number">GEOGRAPHIC COMMUNITY</span><h2>Professional activity rooted in place.</h2></div><p>Local structures help members meet, learn, organise technical programmes and respond to the needs of their maritime communities.</p></div><div class="nimena-hub-grid nimena-hub-grid--three"><article class="nimena-hub-card"><i class="fa-light fa-landmark"></i><h3>National network</h3><p>Institution-wide governance, national programmes, standards dialogue and cross-chapter coordination.</p></article><article class="nimena-hub-card"><i class="fa-light fa-location-dot"></i><h3>Regional &amp; chapter activity</h3><p>Meetings, professional visits, learning events and local industry engagement.</p></article><article class="nimena-hub-card"><i class="fa-light fa-building-columns"></i><h3>Student chapters</h3><p>Institution-linked communities that introduce students to the profession and practising engineers.</p></article></div><div class="nimena-directory-state"><span>Verified chapter directory</span><strong>Chapter contacts and officers will be published after Secretariat verification.</strong><p>This protects members from outdated or unofficial contact information.</p><a href="../contact/">Ask for your nearest chapter</a></div></div></section>
<section class="nimena-hub-section nimena-hub-section--navy" id="technical"><div class="container"><div class="nimena-hub-heading"><div><span class="nimena-programme-number">TECHNICAL PARTICIPATION</span><h2>Turn professional experience into shared capability.</h2></div><p>Working streams can support standards, research, conferences, education, membership and industry engagement once their mandates and officers are formally confirmed.</p></div><div class="nimena-topic-list"><a href="../programmes/#accreditation"><span>Codes, standards &amp; professional quality</span><i class="fa-light fa-arrow-up-right"></i></a><a href="../research/"><span>Research, journals &amp; technical publications</span><i class="fa-light fa-arrow-up-right"></i></a><a href="../conferences/"><span>Conferences, webinars &amp; technical events</span><i class="fa-light fa-arrow-up-right"></i></a><a href="../education-careers/"><span>Education, CPD &amp; career development</span><i class="fa-light fa-arrow-up-right"></i></a><a href="../partnerships/"><span>Business, innovation &amp; industry collaboration</span><i class="fa-light fa-arrow-up-right"></i></a></div></div></section>
<section class="nimena-hub-section" id="emerging"><div class="container"><div class="nimena-split-feature"><div><span class="nimena-programme-number">EMERGING PROFESSIONALS</span><h2>Build belonging before the first senior title.</h2><p>Student and young-professional programmes should connect education to practice through mentoring, technical visits, career conversations, competitions, volunteering and early leadership opportunities.</p><ul class="nimena-check-list"><li>Mentor matching and career conversations</li><li>Industrial visits and technical exposure</li><li>Research, writing and presentation opportunities</li><li>Graduate transition and employability support</li></ul><div class="nimena-programme-actions"><a class="nimena-programme-action" href="../register/">Join NIMENA</a><a class="nimena-programme-action nimena-programme-action--outline" href="../education-careers/">Explore learning &amp; careers</a></div></div><div class="nimena-split-feature__image"><img src="../assets/img/current/singapore-innovation-night-audience.webp" alt="Emerging maritime professionals participating in a NIMENA event" loading="lazy"/></div></div></div></section>
<section class="nimena-hub-section nimena-hub-section--soft" id="volunteer"><div class="container"><div class="nimena-hub-heading"><div><span class="nimena-programme-number">VOLUNTEER &amp; LEAD</span><h2>Contribute time, knowledge and professional judgement.</h2></div><p>Members may express interest in mentoring, technical review, event support, writing, chapter service and other approved volunteer roles. Appointment remains subject to suitability, conflicts and the relevant authority.</p></div><div class="nimena-programme-actions"><a class="nimena-programme-action" href="../login/">Express interest through the portal</a><a class="nimena-programme-action nimena-programme-action--outline" href="../team/">View national leadership</a></div></div></section>
</main>''',
    },
    "education-careers": {
        "title": "Education, CPD & Careers | NIMENA",
        "description": "Explore NIMENA continuing professional development, webinars, technical learning, mentoring, career resources and professional progression.",
        "main": r'''
<main>
<section class="nimena-hub-hero" style="--hub-image:url('../assets/img/nimena/archive/technical-workshop.webp')"><div class="container"><div class="nimena-hub-hero__content"><span class="nimena-programme-eyebrow">Education, CPD &amp; careers</span><h1>Keep learning. Record the evidence. Move the profession forward.</h1><p>A connected route from technical learning and CPD records to mentoring, career opportunity and professional advancement.</p><div class="nimena-programme-actions"><a class="nimena-programme-action" href="../login/">Open learning record</a><a class="nimena-programme-action nimena-programme-action--outline" href="../contact/">Propose a learning programme</a></div></div></div></section>
<nav class="nimena-action-strip" aria-label="Education and career routes"><div class="container"><div class="nimena-action-strip__grid"><a href="#learning"><i class="fa-light fa-chalkboard-user"></i><span><small>Learn</small>Courses &amp; webinars</span></a><a href="#cpd"><i class="fa-light fa-certificate"></i><span><small>Record</small>CPD &amp; certificates</span></a><a href="#careers"><i class="fa-light fa-briefcase"></i><span><small>Advance</small>Careers &amp; mentoring</span></a><a href="#resources"><i class="fa-light fa-books"></i><span><small>Use</small>Professional resources</span></a></div></div></nav>
<section class="nimena-hub-section" id="learning"><div class="container"><div class="nimena-hub-heading"><div><span class="nimena-programme-number">LEARNING DIRECTORY</span><h2>Education organised around professional need.</h2></div><p>Instead of a loose events list, each opportunity should state its audience, learning outcomes, format, facilitator, CPD treatment and registration route.</p></div><div class="nimena-accordion">
<details open><summary><span>Education &amp; professional development</span><i class="fa-light fa-plus"></i></summary><div><a href="../conferences/">Technical webinars and masterclasses</a><a href="../programmes/#accreditation">Approved-provider and endorsed-course directory</a><a href="../portfolio/">Industrial visits and practical exposure</a><a href="../contact/">Request or propose a course</a></div></details>
<details><summary><span>Careers &amp; mentoring</span><i class="fa-light fa-plus"></i></summary><div><a href="#careers">Career pathways and opportunity board</a><a href="#careers">Mentoring and early-career support</a><a href="../community/">Volunteer and committee experience</a><a href="../membership/">Professional progression through membership</a></div></details>
<details><summary><span>Professional resources</span><i class="fa-light fa-plus"></i></summary><div><a href="../research/">Journals, reports and technical papers</a><a href="../magazine/">Industry commentary and practitioner stories</a><a href="../blog/">News, policy and professional insight</a><a href="../login/">Member learning history and saved resources</a></div></details>
</div></div></section>
<section class="nimena-hub-section nimena-hub-section--navy" id="cpd"><div class="container"><div class="nimena-hub-heading"><div><span class="nimena-programme-number">CPD JOURNEY</span><h2>One record from registration to certificate.</h2></div><p>The production portal will connect eligible learning to attendance evidence, CPD decisions and downloadable certificates.</p></div><div class="nimena-step-grid"><article><b>01</b><h3>Discover</h3><p>Filter programmes by topic, level, location, format and date.</p></article><article><b>02</b><h3>Register</h3><p>Use member or non-member pricing where an approved fee applies.</p></article><article><b>03</b><h3>Attend</h3><p>Capture verified attendance through check-in or completion evidence.</p></article><article><b>04</b><h3>Record</h3><p>Add approved CPD value and evidence to the member profile.</p></article><article><b>05</b><h3>Certify</h3><p>Issue a verifiable certificate when programme conditions are met.</p></article></div></div></section>
<section class="nimena-hub-section" id="careers"><div class="container"><div class="nimena-hub-heading"><div><span class="nimena-programme-number">CAREER PATHWAYS</span><h2>See where maritime engineering can take you.</h2></div><p>Career content should connect real disciplines, competencies and professional stories—not simply advertise vacancies.</p></div><div class="nimena-career-grid"><article><img src="../assets/img/nimena/archive/maritime-profession.webp" alt="Marine engineering work around commercial vessels" loading="lazy"/><div><span>Engineering operations</span><h3>Marine engineering</h3><p>Propulsion, machinery, maintenance, reliability, safety and vessel operations.</p></div></article><article><img src="../assets/img/nimena/archive/research-knowledge.webp" alt="Naval architecture and marine design work" loading="lazy"/><div><span>Design &amp; assurance</span><h3>Naval architecture</h3><p>Hull form, structures, stability, hydrodynamics, production and classification.</p></div></article><article><img src="../assets/img/current/singapore-blue-economy-panel.webp" alt="Blue economy and sustainable energy discussion" loading="lazy"/><div><span>Emerging opportunity</span><h3>Offshore &amp; blue economy</h3><p>Offshore systems, coastal resilience, marine energy, policy, innovation and sustainability.</p></div></article></div></div></section>
<section class="nimena-hub-section nimena-hub-section--soft" id="resources"><div class="container"><div class="nimena-split-feature"><div><span class="nimena-programme-number">MEMBER RESOURCE LIBRARY</span><h2>Useful knowledge, retained and searchable.</h2><p>The member portal will become the protected home for saved resources, purchased or member-only publications, learning history and certificates. Public resources remain available through Research, Magazine and News.</p><div class="nimena-programme-actions"><a class="nimena-programme-action" href="../login/">Open member resources</a><a class="nimena-programme-action nimena-programme-action--outline" href="../research/">Browse public research</a></div></div><div class="nimena-resource-stack"><a href="../research/"><i class="fa-light fa-journal-whills"></i><span>Research &amp; journals</span></a><a href="../magazine/"><i class="fa-light fa-newspaper"></i><span>NIMENA Magazine</span></a><a href="../blog/"><i class="fa-light fa-wave-pulse"></i><span>News &amp; industry insight</span></a></div></div></div></section>
</main>''',
    },
    "conferences": {
        "title": "Conferences & Events | NIMENA",
        "description": "Discover NIMENA conferences, webinars, chapter events, delegate registration, calls for abstracts and conference-paper workflows.",
        "main": r'''
<main>
<section class="nimena-hub-hero" style="--hub-image:url('../assets/img/current/singapore-innovation-night.webp')"><div class="container"><div class="nimena-hub-hero__content"><span class="nimena-programme-eyebrow">Conferences &amp; events</span><h1>Where maritime knowledge becomes professional action.</h1><p>Conferences, technical webinars, chapter meetings, industry roundtables and research presentations—connected through one public calendar and one attendee journey.</p><div class="nimena-programme-actions"><a class="nimena-programme-action" href="../login/">Conference workspace</a><a class="nimena-programme-action nimena-programme-action--outline" href="../research/#conferences">Submit conference research</a></div></div></div></section>
<nav class="nimena-action-strip" aria-label="Conference routes"><div class="container"><div class="nimena-action-strip__grid"><a href="#calendar"><i class="fa-light fa-calendar-days"></i><span><small>Discover</small>Event calendar</span></a><a href="#delegate"><i class="fa-light fa-ticket"></i><span><small>Attend</small>Delegate registration</span></a><a href="#cfp"><i class="fa-light fa-file-lines"></i><span><small>Contribute</small>Conference CFP</span></a><a href="../portfolio/"><i class="fa-light fa-images"></i><span><small>Review</small>Past activities</span></a></div></div></nav>
<section class="nimena-hub-section" id="calendar"><div class="container"><div class="nimena-hub-heading"><div><span class="nimena-programme-number">EVENT DIRECTORY</span><h2>One place for every approved NIMENA gathering.</h2></div><p>Dates and venues will appear only after approval. The structure below is ready for the Secretariat to publish confirmed programmes without redesigning the site.</p></div><div class="nimena-event-grid"><article><div class="nimena-event-card__date"><strong>Annual</strong><span>National</span></div><div><span>Flagship gathering</span><h3>Conference &amp; Annual General Meeting</h3><p>Technical sessions, governance, professional networking, exhibitions and institutional business.</p><a href="../contact/">Request conference information</a></div></article><article><div class="nimena-event-card__date"><strong>Online</strong><span>Technical</span></div><div><span>Continuous learning</span><h3>Webinars &amp; masterclasses</h3><p>Focused professional learning delivered by practitioners, researchers and industry partners.</p><a href="../education-careers/">Explore professional learning</a></div></article><article><div class="nimena-event-card__date"><strong>Local</strong><span>Chapters</span></div><div><span>Professional community</span><h3>Chapter meetings &amp; technical visits</h3><p>Local networking, facility exposure, member engagement and career development.</p><a href="../community/">Find community routes</a></div></article><article><div class="nimena-event-card__date"><strong>Industry</strong><span>Global</span></div><div><span>Collaboration</span><h3>Innovation nights &amp; roundtables</h3><p>Problem owners, engineers, startups, researchers and investors exploring practical solutions.</p><a href="../programmes/#innovation">Explore innovation programmes</a></div></article></div></div></section>
<section class="nimena-hub-section nimena-hub-section--navy" id="delegate"><div class="container"><div class="nimena-hub-heading"><div><span class="nimena-programme-number">DELEGATE JOURNEY</span><h2>From event discovery to verified participation.</h2></div><p>The conference module prototype is designed for members and non-members, with approved pricing and certificates added only when NIMENA confirms the rules.</p></div><div class="nimena-step-grid"><article><b>01</b><h3>Select</h3><p>Choose an event, ticket type, attendance mode and optional activities.</p></article><article><b>02</b><h3>Register</h3><p>Provide delegate details and apply a verified member rate where applicable.</p></article><article><b>03</b><h3>Pay</h3><p>Complete secure payment and receive an invoice or receipt.</p></article><article><b>04</b><h3>Check in</h3><p>Use a unique registration record or QR code to verify attendance.</p></article><article><b>05</b><h3>Receive record</h3><p>Add eligible CPD and certificates to the attendee profile.</p></article></div></div></section>
<section class="nimena-hub-section" id="cfp"><div class="container"><div class="nimena-split-feature"><div class="nimena-split-feature__image"><img src="../assets/img/current/singapore-blue-economy-panel.webp" alt="Maritime experts participating in a technical panel" loading="lazy"/></div><div><span class="nimena-programme-number">CONFERENCE CALL FOR PAPERS</span><h2>A review route designed for programmes and proceedings.</h2><p>Authors can submit an abstract or full paper to an approved conference track. Review, decision, revision and scheduling remain separate from journal acceptance.</p><ul class="nimena-check-list"><li>Track, topic, format and deadline selection</li><li>Blind review and conflict-of-interest declarations</li><li>Scored recommendations and authorised decisions</li><li>Speaker profile, programme scheduling and presentation status</li><li>Proceedings or optional invitation to a journal special issue</li></ul><div class="nimena-programme-actions"><a class="nimena-programme-action" href="../login/">Preview conference submission</a><a class="nimena-programme-action nimena-programme-action--outline" href="../news-call-for-papers/">Journal Call for Papers</a></div></div></div></div></section>
<section class="nimena-hub-cta"><div class="container"><div><span>Industry participation</span><h2>Host, sponsor, exhibit or contribute technical expertise.</h2></div><div><a href="../partnerships/">Partnership options</a><a href="../contact/">Contact the Secretariat</a></div></div></section>
</main>''',
    },
    "recognition": {
        "title": "Recognition, Awards & Scholarships | NIMENA",
        "description": "Explore NIMENA's proposed professional recognition, awards, Fellowship, scholarships, nominations and verified recipient archive.",
        "main": r'''
<main>
<section class="nimena-hub-hero" style="--hub-image:url('../assets/img/nimena/archive/gallery-recognition.webp')"><div class="container"><div class="nimena-hub-hero__content"><span class="nimena-programme-eyebrow">Recognition, awards &amp; scholarships</span><h1>Recognise achievement without weakening the standard.</h1><p>A transparent home for professional awards, Fellowship, scholarships, nominations and verified recipient records.</p><div class="nimena-programme-actions"><a class="nimena-programme-action" href="#programmes">Explore recognition routes</a><a class="nimena-programme-action nimena-programme-action--outline" href="../login/">Nomination workspace</a></div></div></div></section>
<nav class="nimena-action-strip" aria-label="Recognition routes"><div class="container"><div class="nimena-action-strip__grid"><a href="#programmes"><i class="fa-light fa-medal"></i><span><small>Honour</small>Medals &amp; awards</span></a><a href="#programmes"><i class="fa-light fa-user-tie"></i><span><small>Recognise</small>Fellowship</span></a><a href="#programmes"><i class="fa-light fa-graduation-cap"></i><span><small>Support</small>Scholarships &amp; grants</span></a><a href="#archive"><i class="fa-light fa-trophy-star"></i><span><small>Verify</small>Recipients &amp; winners</span></a></div></div></nav>
<section class="nimena-hub-section" id="programmes"><div class="container"><div class="nimena-hub-heading"><div><span class="nimena-programme-number">RECOGNITION ARCHITECTURE</span><h2>Different achievements need different evidence.</h2></div><p>NIMENA must approve the final programme names, criteria, nomination authority and decision panels before any call opens.</p></div><div class="nimena-hub-grid nimena-hub-grid--four"><article class="nimena-hub-card"><i class="fa-light fa-medal"></i><h3>Professional medals</h3><p>Exceptional technical, leadership, service or innovation achievements assessed against published criteria.</p></article><article class="nimena-hub-card"><i class="fa-light fa-award"></i><h3>Institutional awards</h3><p>Recognition for members, teams, chapters, projects or organisations making a verified contribution.</p></article><article class="nimena-hub-card"><i class="fa-light fa-user-crown"></i><h3>Fellowship</h3><p>A senior professional recognition route with eligibility, sponsors, evidence and formal approval.</p></article><article class="nimena-hub-card"><i class="fa-light fa-book-open-reader"></i><h3>Scholarships &amp; grants</h3><p>Competitive support for learning, research, travel or professional development when funding is approved.</p></article></div></div></section>
<section class="nimena-hub-section nimena-hub-section--navy"><div class="container"><div class="nimena-hub-heading"><div><span class="nimena-programme-number">NOMINATION GOVERNANCE</span><h2>Every decision should be explainable.</h2></div><p>Recognition creates credibility only when conflicts, evidence and authority are properly controlled.</p></div><div class="nimena-step-grid"><article><b>01</b><h3>Publish call</h3><p>State the category, criteria, deadline, evidence and who may nominate.</p></article><article><b>02</b><h3>Check eligibility</h3><p>Confirm membership or category rules and require complete declarations.</p></article><article><b>03</b><h3>Independent review</h3><p>Use approved reviewers, declared conflicts and documented scoring.</p></article><article><b>04</b><h3>Authorised decision</h3><p>Record the recommendation, approving authority and decision basis.</p></article><article><b>05</b><h3>Publish &amp; retain</h3><p>Add verified recipients to the archive and preserve the audit history.</p></article></div></div></section>
<section class="nimena-hub-section" id="archive"><div class="container"><div class="nimena-hub-heading"><div><span class="nimena-programme-number">VERIFIED ARCHIVE</span><h2>Recipients, citations and programme years.</h2></div><p>The public archive will allow visitors to verify an award or recognition without exposing private nomination material.</p></div><div class="nimena-directory-state"><span>Recognition archive</span><strong>No new programme records have been approved for this redesigned archive.</strong><p>Historical records can be imported after the Secretariat verifies names, titles, categories, citations and dates.</p><a href="../contact/">Contact the Secretariat about a record</a></div></div></section>
<section class="nimena-hub-cta"><div class="container"><div><span>Programme design</span><h2>Help NIMENA establish credible recognition and scholarship pathways.</h2></div><div><a href="../partnerships/">Fund a programme</a><a href="../contact/">Discuss governance</a></div></div></section>
</main>''',
    },
    "partnerships": {
        "title": "Industry Partnerships & Sponsorships | NIMENA",
        "description": "Partner with NIMENA on professional development, research, conferences, innovation, scholarships, publications and maritime capability.",
        "main": r'''
<main>
<section class="nimena-hub-hero" style="--hub-image:url('../assets/img/current/singapore-innovation-night-engagement.webp')"><div class="container"><div class="nimena-hub-hero__content"><span class="nimena-programme-eyebrow">Industry partnerships &amp; sponsorships</span><h1>Collaboration built around outcomes—not logo placement.</h1><p>A governed route for companies, universities, public bodies, development partners and media organisations to support maritime capability while protecting NIMENA's independence.</p><div class="nimena-programme-actions"><a class="nimena-programme-action" href="#routes">Explore partnership routes</a><a class="nimena-programme-action nimena-programme-action--outline" href="../contact/">Propose a collaboration</a></div></div></div></section>
<nav class="nimena-action-strip" aria-label="Partnership routes"><div class="container"><div class="nimena-action-strip__grid"><a href="#corporate"><i class="fa-light fa-building"></i><span><small>Join</small>Corporate programme</span></a><a href="#academic"><i class="fa-light fa-building-columns"></i><span><small>Connect</small>Academic affiliates</span></a><a href="#routes"><i class="fa-light fa-hand-holding-dollar"></i><span><small>Support</small>Programme sponsorship</span></a><a href="#governance"><i class="fa-light fa-shield-check"></i><span><small>Understand</small>Partnership governance</span></a></div></div></nav>
<section class="nimena-hub-section" id="routes"><div class="container"><div class="nimena-hub-heading"><div><span class="nimena-programme-number">WAYS TO COLLABORATE</span><h2>Match institutional need with credible partner capability.</h2></div><p>Each collaboration should have a defined owner, purpose, contribution, benefit, safeguard and outcome report.</p></div><div class="nimena-hub-grid nimena-hub-grid--four"><article class="nimena-hub-card"><i class="fa-light fa-chalkboard-user"></i><h3>Skills &amp; CPD</h3><p>Courses, masterclasses, technical visits, equipment demonstrations and practitioner learning.</p></article><article class="nimena-hub-card"><i class="fa-light fa-flask"></i><h3>Research &amp; standards</h3><p>Reports, data, laboratories, technical panels and responsible knowledge partnerships.</p></article><article class="nimena-hub-card"><i class="fa-light fa-calendar-star"></i><h3>Events &amp; conferences</h3><p>Programme, exhibition, delegate, venue, speaker and conference-support opportunities.</p></article><article class="nimena-hub-card"><i class="fa-light fa-lightbulb-on"></i><h3>Innovation &amp; transfer</h3><p>Problem statements, pilots, startup showcases, mentors, investment and commercialisation.</p></article><article class="nimena-hub-card"><i class="fa-light fa-graduation-cap"></i><h3>Scholarships &amp; careers</h3><p>Student support, mentoring, internships, graduate development and professional opportunity.</p></article><article class="nimena-hub-card"><i class="fa-light fa-newspaper"></i><h3>Publishing &amp; media</h3><p>Magazine, responsible advertising, public education and knowledge-distribution support.</p></article><article class="nimena-hub-card"><i class="fa-light fa-screwdriver-wrench"></i><h3>Facilities &amp; equipment</h3><p>Laboratory, software, training, data and in-kind contributions with documented conditions.</p></article><article class="nimena-hub-card"><i class="fa-light fa-leaf"></i><h3>Blue-economy programmes</h3><p>Sustainable marine industry, coastal resilience, local capacity and energy initiatives.</p></article></div></div></section>
<section class="nimena-hub-section nimena-hub-section--navy" id="corporate"><div class="container"><div class="nimena-hub-heading"><div><span class="nimena-programme-number">CORPORATE PARTNERSHIP PROGRAMME</span><h2>A scalable structure for sustained participation.</h2></div><p>These working level names organise the prototype. NIMENA must approve final benefits, fees, duration and eligibility before enrolment.</p></div><div class="nimena-tier-grid"><article><span>Level 01</span><h3>Strategic Partner</h3><p>Multi-programme, senior-level collaboration with an agreed annual outcome plan.</p></article><article><span>Level 02</span><h3>Programme Partner</h3><p>Focused support for a defined conference, research, learning or innovation programme.</p></article><article><span>Level 03</span><h3>Supporting Partner</h3><p>Targeted financial or in-kind contribution with proportionate acknowledgement.</p></article><article><span>Level 04</span><h3>Community Partner</h3><p>Local, chapter, student or emerging-professional support under an approved agreement.</p></article></div></div></section>
<section class="nimena-hub-section" id="academic"><div class="container"><div class="nimena-split-feature"><div><span class="nimena-programme-number">ACADEMIC &amp; KNOWLEDGE AFFILIATES</span><h2>Connect education, research and professional practice.</h2><p>Universities, training organisations and research centres can work with NIMENA on student development, curriculum dialogue, conferences, research, facilities and knowledge exchange without implying statutory accreditation.</p><ul class="nimena-check-list"><li>Student and graduate transition programmes</li><li>Joint seminars, technical visits and research activity</li><li>Editorial, reviewer and subject-expert participation</li><li>Laboratory, data and specialist facility collaboration</li></ul><div class="nimena-programme-actions"><a class="nimena-programme-action" href="../programmes/#accreditation">Accreditation &amp; endorsement</a><a class="nimena-programme-action nimena-programme-action--outline" href="../contact/">Discuss affiliation</a></div></div><div class="nimena-split-feature__image"><img src="../assets/img/current/singapore-innovation-night-panel.webp" alt="NIMENA industry and knowledge partners in discussion" loading="lazy"/></div></div></div></section>
<section class="nimena-hub-section nimena-hub-section--soft" id="governance"><div class="container"><div class="nimena-hub-heading"><div><span class="nimena-programme-number">PARTNERSHIP GOVERNANCE</span><h2>Trust depends on clear boundaries.</h2></div><p>Sponsorship can enable programmes, but it must never purchase editorial decisions, professional recognition, accreditation outcomes or research conclusions.</p></div><div class="nimena-topic-list nimena-topic-list--light"><div><span>Due diligence and conflict checks</span><i class="fa-light fa-shield-check"></i></div><div><span>Written scope, responsibilities and benefits</span><i class="fa-light fa-file-contract"></i></div><div><span>Approved brand and acknowledgement rules</span><i class="fa-light fa-copyright"></i></div><div><span>Outcome, finance and in-kind reporting</span><i class="fa-light fa-chart-mixed"></i></div><div><span>Editorial and professional independence</span><i class="fa-light fa-scale-balanced"></i></div></div><div class="nimena-directory-state"><span>Approved partner directory</span><strong>No organisations are listed until NIMENA verifies the agreement and publication permission.</strong><p>The future directory will identify the partnership type, approved term and supported programme.</p></div></div></section>
<section class="nimena-hub-cta"><div class="container"><div><span>Start a serious conversation</span><h2>Bring a problem, capability or programme—not just a sponsorship request.</h2></div><div><a href="../contact/">Propose a collaboration</a><a href="../programmes/">View institutional programmes</a></div></div></section>
</main>''',
    },
    "search": {
        "title": "Search NIMENA",
        "description": "Search NIMENA membership, research, journals, events, education, careers, recognition, partnerships, news and professional resources.",
        "main": r'''
<main>
<section class="nimena-search-hero" style="--search-hero:url('../assets/img/nimena/archive/hero-shipyard.webp')"><div class="container"><span class="nimena-programme-eyebrow">Find information</span><h1>Search NIMENA</h1><p>Search public membership, learning, events, research, publications, recognition, community and industry resources.</p></div></section>
<section class="nimena-search-page"><div class="container"><form class="nimena-search-form" id="nimena-site-search" role="search"><label for="nimena-search-query">What are you looking for?</label><div><input id="nimena-search-query" name="q" type="search" autocomplete="off" placeholder="Try membership, conferences, journals or careers"/><button type="submit">Search</button></div></form><div class="nimena-search-summary" id="nimena-search-summary" aria-live="polite">Enter a keyword to search NIMENA's public resources.</div><div class="nimena-search-results" id="nimena-search-results"></div><noscript><p class="nimena-directory-state">JavaScript is required for this public-site search. You can still use the main navigation above.</p></noscript></div></section>
</main>''',
    },
}


def replace_meta(html: str, slug: str, title: str, description: str) -> str:
    url = f"https://nimena.org.ng/{slug}/"
    html = re.sub(r"<title>.*?</title>", f"<title>{title}</title>", html, count=1, flags=re.S)
    html = re.sub(
        r'<meta content="[^"]*" name="description"/>',
        f'<meta content="{description}" name="description"/>',
        html,
        count=1,
    )
    html = re.sub(r'<link href="[^"]*" rel="canonical"/>', f'<link href="{url}" rel="canonical"/>', html, count=1)
    for prop, value in (("og:title", title), ("og:description", description), ("og:url", url)):
        html = re.sub(
            rf'<meta content="[^"]*" property="{re.escape(prop)}"/>',
            f'<meta content="{value}" property="{prop}"/>',
            html,
            count=1,
        )
    for name, value in (("twitter:title", title), ("twitter:description", description), ("twitter:url", url)):
        html = re.sub(
            rf'<meta content="[^"]*" name="{re.escape(name)}"/>',
            f'<meta content="{value}" name="{name}"/>',
            html,
            count=1,
        )
    return html


for slug, page in PAGES.items():
    output = replace_meta(TEMPLATE, slug, page["title"], page["description"])
    output = re.sub(r"<body>", f'<body class="nimena-public-page nimena-page-{slug}">', output, count=1)
    output = re.sub(r"<main>.*?</main>", page["main"].strip(), output, count=1, flags=re.S)
    if slug == "search":
        output = output.replace(
            '<script src="../assets/js/main.js?v=20260912-3"></script>',
            '<script src="../assets/js/site-search.js?v=20260929-1"></script>\n<script src="../assets/js/main.js?v=20260912-3"></script>',
        )
    target = ROOT / slug / "index.html"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(output, encoding="utf-8")
    print(target.relative_to(ROOT))
